services:
  db:
    # Database: Actual = Postgres
    image: 'postgres:latest'
    container_name: oxy-postgres
    environment:
      POSTGRES_DB: library-dev
      POSTGRES_PASSWORD: admin
      TZ: America/Sao_Paulo
    ports:
      - "5432"
    #volumes:
    #- ~/docker/data:/var/lib/postgresql/data
    networks:
      - oxy-compose-network

  dbms:
    # Database Management System
    image: dpage/pgadmin4:latest
    container_name: oxy-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "16543:80"
    depends_on:
      - db
    networks:
      - oxy-compose-network

networks:
  oxy-compose-network:
    driver: bridge
