spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    database: postgresql
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    clean-disabled: false
