spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/library-dev}
    username: ${DATASOURCE_USER:postgres}
    password: ${DATASOURCE_PASS:admin}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    database: postgresql
  flyway:
    clean-disabled: false
